apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesimplify
spec:
  selector:
    matchLabels:
      app: kubesimplify
  template:
    metadata:
      labels:
        app: kubesimplify
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: saiyam911/kubeworkshop:sha-14697f8
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: kubesimplify
spec:
  selector:
    app: kubesimplify
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort

